### ISSUE TITLE
settings.json not in files

### ISSUE THREAD

**Issue by YannickGTHD** [Kuroosh/altV-PlayerBlips#1]
Hey, I'm currently setting up a little Server for me and my friends. The settings.json you mentioned and which is required in the code, is not within the files. 
I'm not really into coding, just starting to learn a bit. Would be great if you can tell me what should be in there. I think just the blip-color?
Thank you for your time!

**Comment by Kuroosh** [comment]
Hi,

just create a file inside the resource called `settings.json` & put following code inside : 

```json
{
   "RandomColor": true,
   "StandardColor": 52,
   "UpdateInterval": 1000
}
```

Greetings 
VenoX International | Kuroosh
